global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "concord-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:5050"]
        labels:
          service: "concord-api"
